name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 8
          cache: maven
      - name: Build with Maven
        env:
          AWS_REGION: us-west-2
        run: mvn -ntp -U verify
      - name: Upload Failed Test Report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Failed Test Report
          path: target/surefire-reports
